version: '3.9'
services:
  db:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
  app:
    container_name: app
    depends_on:
      - db
    build: .
    command: bash -c 'npm start'
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
      SERVER_NAME: challenge-walmart
      PORT: 3001
      HOST: localhost

volumes:
  db-data: {}
